/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import ru.sidnystorm.books.model.tables.BookProsvetBl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookProsvetBlRecord extends UpdatableRecordImpl<BookProsvetBlRecord> implements Record5<Integer, String, String, String, Double> {

    private static final long serialVersionUID = 625117522;

    /**
     * Setter for <code>public.book_prosvet_bl.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book_prosvet_bl.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.book_prosvet_bl.author</code>.
     */
    public void setAuthor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book_prosvet_bl.author</code>.
     */
    public String getAuthor() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.book_prosvet_bl.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.book_prosvet_bl.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.book_prosvet_bl.grade</code>.
     */
    public void setGrade(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.book_prosvet_bl.grade</code>.
     */
    public String getGrade() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.book_prosvet_bl.price</code>.
     */
    public void setPrice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.book_prosvet_bl.price</code>.
     */
    public Double getPrice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BookProsvetBl.BOOK_PROSVET_BL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BookProsvetBl.BOOK_PROSVET_BL.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BookProsvetBl.BOOK_PROSVET_BL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BookProsvetBl.BOOK_PROSVET_BL.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return BookProsvetBl.BOOK_PROSVET_BL.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord value2(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord value4(String value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord value5(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetBlRecord values(Integer value1, String value2, String value3, String value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookProsvetBlRecord
     */
    public BookProsvetBlRecord() {
        super(BookProsvetBl.BOOK_PROSVET_BL);
    }

    /**
     * Create a detached, initialised BookProsvetBlRecord
     */
    public BookProsvetBlRecord(Integer id, String author, String name, String grade, Double price) {
        super(BookProsvetBl.BOOK_PROSVET_BL);

        set(0, id);
        set(1, author);
        set(2, name);
        set(3, grade);
        set(4, price);
    }
}
