/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import ru.sidnystorm.books.model.tables.OrderBook;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderBookRecord extends UpdatableRecordImpl<OrderBookRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1222053917;

    /**
     * Setter for <code>public.order_book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.order_book.order</code>.
     */
    public void setOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_book.order</code>.
     */
    public Integer getOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_book.book</code>.
     */
    public void setBook(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_book.book</code>.
     */
    public Integer getBook() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.order_book.count</code>.
     */
    public void setCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_book.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderBook.ORDER_BOOK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderBook.ORDER_BOOK.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderBook.ORDER_BOOK.BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OrderBook.ORDER_BOOK.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getBook();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBook();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderBookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderBookRecord value2(Integer value) {
        setOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderBookRecord value3(Integer value) {
        setBook(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderBookRecord value4(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderBookRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderBookRecord
     */
    public OrderBookRecord() {
        super(OrderBook.ORDER_BOOK);
    }

    /**
     * Create a detached, initialised OrderBookRecord
     */
    public OrderBookRecord(Integer id, Integer order, Integer book, Integer count) {
        super(OrderBook.ORDER_BOOK);

        set(0, id);
        set(1, order);
        set(2, book);
        set(3, count);
    }
}
