/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import ru.sidnystorm.books.model.enums.Role;
import ru.sidnystorm.books.model.tables.Users;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record18<Integer, String, String, Role, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 852018583;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.users.login</code>.
     */
    public void setLogin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.role</code>.
     */
    public void setRole(Role value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.role</code>.
     */
    public Role getRole() {
        return (Role) get(3);
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.inn</code>.
     */
    public void setInn(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.inn</code>.
     */
    public String getInn() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.kpp</code>.
     */
    public void setKpp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.kpp</code>.
     */
    public String getKpp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.ogrn</code>.
     */
    public void setOgrn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.ogrn</code>.
     */
    public String getOgrn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users.okpo</code>.
     */
    public void setOkpo(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.okpo</code>.
     */
    public String getOkpo() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.users.bank</code>.
     */
    public void setBank(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.bank</code>.
     */
    public String getBank() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.users.bik</code>.
     */
    public void setBik(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.users.bik</code>.
     */
    public String getBik() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.users.bank_address</code>.
     */
    public void setBankAddress(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.users.bank_address</code>.
     */
    public String getBankAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.users.checking_account</code>.
     */
    public void setCheckingAccount(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.users.checking_account</code>.
     */
    public String getCheckingAccount() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.users.correspondent_account</code>.
     */
    public void setCorrespondentAccount(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.users.correspondent_account</code>.
     */
    public String getCorrespondentAccount() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.users.phone</code>.
     */
    public void setPhone(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public void setEmail(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.users.manager</code>.
     */
    public void setManager(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.users.manager</code>.
     */
    public Integer getManager() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, String, Role, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, String, Role, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Role> field4() {
        return Users.USERS.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.INN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Users.USERS.KPP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.OGRN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users.USERS.OKPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.BANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Users.USERS.BIK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Users.USERS.BANK_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Users.USERS.CHECKING_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Users.USERS.CORRESPONDENT_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Users.USERS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Users.USERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Users.USERS.MANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Role component4() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getKpp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getOkpo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getBik();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getBankAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCheckingAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCorrespondentAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getManager();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Role value4() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getKpp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getOkpo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getBik();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getBankAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCheckingAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCorrespondentAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getManager();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Role value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setInn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(String value) {
        setKpp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setOgrn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(String value) {
        setOkpo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setBank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value12(String value) {
        setBik(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value13(String value) {
        setBankAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value14(String value) {
        setCheckingAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value15(String value) {
        setCorrespondentAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value16(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value17(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value18(Integer value) {
        setManager(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(Integer value1, String value2, String value3, Role value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String login, String password, Role role, String name, String address, String inn, String kpp, String ogrn, String okpo, String bank, String bik, String bankAddress, String checkingAccount, String correspondentAccount, String phone, String email, Integer manager) {
        super(Users.USERS);

        set(0, id);
        set(1, login);
        set(2, password);
        set(3, role);
        set(4, name);
        set(5, address);
        set(6, inn);
        set(7, kpp);
        set(8, ogrn);
        set(9, okpo);
        set(10, bank);
        set(11, bik);
        set(12, bankAddress);
        set(13, checkingAccount);
        set(14, correspondentAccount);
        set(15, phone);
        set(16, email);
        set(17, manager);
    }
}
