/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import ru.sidnystorm.books.model.tables.*;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BOOK_ACADEM_PKEY = Indexes0.BOOK_ACADEM_PKEY;
    public static final Index BOOK_BINOM_PKEY = Indexes0.BOOK_BINOM_PKEY;
    public static final Index BOOK_DROFA_PKEY = Indexes0.BOOK_DROFA_PKEY;
    public static final Index BOOK_PROSVET_BL_PKEY = Indexes0.BOOK_PROSVET_BL_PKEY;
    public static final Index BOOK_PROSVET_PKEY = Indexes0.BOOK_PROSVET_PKEY;
    public static final Index BOOK_PROSVET_ME_PKEY = Indexes0.BOOK_PROSVET_ME_PKEY;
    public static final Index BOOK_PROSVET_SH_PKEY = Indexes0.BOOK_PROSVET_SH_PKEY;
    public static final Index BOOK_PROSVET_VU_PKEY = Indexes0.BOOK_PROSVET_VU_PKEY;
    public static final Index BOOK_RUWORD_PKEY = Indexes0.BOOK_RUWORD_PKEY;
    public static final Index BOOK_VENTANA_PKEY = Indexes0.BOOK_VENTANA_PKEY;
    public static final Index BOOK_XXI_PKEY = Indexes0.BOOK_XXI_PKEY;
    public static final Index MANAGER_PKEY = Indexes0.MANAGER_PKEY;
    public static final Index ORDER_PKEY = Indexes0.ORDER_PKEY;
    public static final Index ORDER_BOOK_PKEY = Indexes0.ORDER_BOOK_PKEY;
    public static final Index PUBLISHER_PKEY = Indexes0.PUBLISHER_PKEY;
    public static final Index USERS_LOGIN_KEY = Indexes0.USERS_LOGIN_KEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BOOK_ACADEM_PKEY = Internal.createIndex("book_academ_pkey", BookAcadem.BOOK_ACADEM, new OrderField[] { BookAcadem.BOOK_ACADEM.ID }, true);
        public static Index BOOK_BINOM_PKEY = Internal.createIndex("book_binom_pkey", BookBinom.BOOK_BINOM, new OrderField[] { BookBinom.BOOK_BINOM.ID }, true);
        public static Index BOOK_DROFA_PKEY = Internal.createIndex("book_drofa_pkey", BookDrofa.BOOK_DROFA, new OrderField[] { BookDrofa.BOOK_DROFA.ID }, true);
        public static Index BOOK_PROSVET_BL_PKEY = Internal.createIndex("book_prosvet_bl_pkey", BookProsvetBl.BOOK_PROSVET_BL, new OrderField[] { BookProsvetBl.BOOK_PROSVET_BL.ID }, true);
        public static Index BOOK_PROSVET_PKEY = Internal.createIndex("book_prosvet_pkey", BookProsvetFp.BOOK_PROSVET_FP, new OrderField[] { BookProsvetFp.BOOK_PROSVET_FP.ID }, true);
        public static Index BOOK_PROSVET_ME_PKEY = Internal.createIndex("book_prosvet_me_pkey", BookProsvetMe.BOOK_PROSVET_ME, new OrderField[] { BookProsvetMe.BOOK_PROSVET_ME.ID }, true);
        public static Index BOOK_PROSVET_SH_PKEY = Internal.createIndex("book_prosvet_sh_pkey", BookProsvetSh.BOOK_PROSVET_SH, new OrderField[] { BookProsvetSh.BOOK_PROSVET_SH.ID }, true);
        public static Index BOOK_PROSVET_VU_PKEY = Internal.createIndex("book_prosvet_vu_pkey", BookProsvetVu.BOOK_PROSVET_VU, new OrderField[] { BookProsvetVu.BOOK_PROSVET_VU.ID }, true);
        public static Index BOOK_RUWORD_PKEY = Internal.createIndex("book_ruword_pkey", BookRuword.BOOK_RUWORD, new OrderField[] { BookRuword.BOOK_RUWORD.ID }, true);
        public static Index BOOK_VENTANA_PKEY = Internal.createIndex("book_ventana_pkey", BookVentana.BOOK_VENTANA, new OrderField[] { BookVentana.BOOK_VENTANA.ID }, true);
        public static Index BOOK_XXI_PKEY = Internal.createIndex("book_xxi_pkey", BookXxi.BOOK_XXI, new OrderField[] { BookXxi.BOOK_XXI.ID }, true);
        public static Index MANAGER_PKEY = Internal.createIndex("manager_pkey", Manager.MANAGER, new OrderField[] { Manager.MANAGER.ID }, true);
        public static Index ORDER_PKEY = Internal.createIndex("order_pkey", Order.ORDER, new OrderField[] { Order.ORDER.ID }, true);
        public static Index ORDER_BOOK_PKEY = Internal.createIndex("order_book_pkey", OrderBook.ORDER_BOOK, new OrderField[] { OrderBook.ORDER_BOOK.ID }, true);
        public static Index PUBLISHER_PKEY = Internal.createIndex("publisher_pkey", Publisher.PUBLISHER, new OrderField[] { Publisher.PUBLISHER.ID }, true);
        public static Index USERS_LOGIN_KEY = Internal.createIndex("users_login_key", Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
