/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model;


import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.sidnystorm.books.model.tables.*;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 412264870;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.book_academ</code>.
     */
    public final BookAcadem BOOK_ACADEM = BookAcadem.BOOK_ACADEM;

    /**
     * The table <code>public.book_binom</code>.
     */
    public final BookBinom BOOK_BINOM = BookBinom.BOOK_BINOM;

    /**
     * The table <code>public.book_drofa</code>.
     */
    public final BookDrofa BOOK_DROFA = BookDrofa.BOOK_DROFA;

    /**
     * The table <code>public.book_prosvet_bl</code>.
     */
    public final BookProsvetBl BOOK_PROSVET_BL = BookProsvetBl.BOOK_PROSVET_BL;

    /**
     * The table <code>public.book_prosvet_fp</code>.
     */
    public final BookProsvetFp BOOK_PROSVET_FP = BookProsvetFp.BOOK_PROSVET_FP;

    /**
     * The table <code>public.book_prosvet_me</code>.
     */
    public final BookProsvetMe BOOK_PROSVET_ME = BookProsvetMe.BOOK_PROSVET_ME;

    /**
     * The table <code>public.book_prosvet_sh</code>.
     */
    public final BookProsvetSh BOOK_PROSVET_SH = BookProsvetSh.BOOK_PROSVET_SH;

    /**
     * The table <code>public.book_prosvet_vu</code>.
     */
    public final BookProsvetVu BOOK_PROSVET_VU = BookProsvetVu.BOOK_PROSVET_VU;

    /**
     * The table <code>public.book_ruword</code>.
     */
    public final BookRuword BOOK_RUWORD = BookRuword.BOOK_RUWORD;

    /**
     * The table <code>public.book_ventana</code>.
     */
    public final BookVentana BOOK_VENTANA = BookVentana.BOOK_VENTANA;

    /**
     * The table <code>public.book_xxi</code>.
     */
    public final BookXxi BOOK_XXI = BookXxi.BOOK_XXI;

    /**
     * The table <code>public.manager</code>.
     */
    public final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>public.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_book</code>.
     */
    public final OrderBook ORDER_BOOK = OrderBook.ORDER_BOOK;

    /**
     * The table <code>public.publisher</code>.
     */
    public final Publisher PUBLISHER = Publisher.PUBLISHER;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BOOK_ACADEM_ID_SEQ,
            Sequences.BOOK_BINOM_ID_SEQ,
            Sequences.BOOK_DROFA_ID_SEQ,
            Sequences.BOOK_PROSVET_BL_ID_SEQ,
            Sequences.BOOK_PROSVET_ID_SEQ,
            Sequences.BOOK_PROSVET_ME_ID_SEQ,
            Sequences.BOOK_PROSVET_SH_ID_SEQ,
            Sequences.BOOK_PROSVET_VU_ID_SEQ,
            Sequences.BOOK_RUWORD_ID_SEQ,
            Sequences.BOOK_VENTANA_ID_SEQ,
            Sequences.BOOK_XXI_ID_SEQ,
            Sequences.MANAGER_ID_SEQ,
            Sequences.ORDER_BOOK_ID_SEQ,
            Sequences.ORDER_ID_SEQ,
            Sequences.PUBLISHER_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BookAcadem.BOOK_ACADEM,
            BookBinom.BOOK_BINOM,
            BookDrofa.BOOK_DROFA,
            BookProsvetBl.BOOK_PROSVET_BL,
            BookProsvetFp.BOOK_PROSVET_FP,
            BookProsvetMe.BOOK_PROSVET_ME,
            BookProsvetSh.BOOK_PROSVET_SH,
            BookProsvetVu.BOOK_PROSVET_VU,
            BookRuword.BOOK_RUWORD,
            BookVentana.BOOK_VENTANA,
            BookXxi.BOOK_XXI,
            Manager.MANAGER,
            Order.ORDER,
            OrderBook.ORDER_BOOK,
            Publisher.PUBLISHER,
            Users.USERS);
    }
}
