/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.Generated;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.book_academ_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_ACADEM_ID_SEQ = new SequenceImpl<Integer>("book_academ_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_binom_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_BINOM_ID_SEQ = new SequenceImpl<Integer>("book_binom_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_drofa_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_DROFA_ID_SEQ = new SequenceImpl<Integer>("book_drofa_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_prosvet_bl_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_PROSVET_BL_ID_SEQ = new SequenceImpl<Integer>("book_prosvet_bl_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_prosvet_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_PROSVET_ID_SEQ = new SequenceImpl<Integer>("book_prosvet_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_prosvet_me_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_PROSVET_ME_ID_SEQ = new SequenceImpl<Integer>("book_prosvet_me_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_prosvet_sh_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_PROSVET_SH_ID_SEQ = new SequenceImpl<Integer>("book_prosvet_sh_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_prosvet_vu_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_PROSVET_VU_ID_SEQ = new SequenceImpl<Integer>("book_prosvet_vu_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_ruword_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_RUWORD_ID_SEQ = new SequenceImpl<Integer>("book_ruword_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_ventana_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_VENTANA_ID_SEQ = new SequenceImpl<Integer>("book_ventana_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_xxi_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_XXI_ID_SEQ = new SequenceImpl<Integer>("book_xxi_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.manager_id_seq</code>
     */
    public static final Sequence<Integer> MANAGER_ID_SEQ = new SequenceImpl<Integer>("manager_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.order_book_id_seq</code>
     */
    public static final Sequence<Integer> ORDER_BOOK_ID_SEQ = new SequenceImpl<Integer>("order_book_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.order_id_seq</code>
     */
    public static final Sequence<Integer> ORDER_ID_SEQ = new SequenceImpl<Integer>("order_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.publisher_id_seq</code>
     */
    public static final Sequence<Integer> PUBLISHER_ID_SEQ = new SequenceImpl<Integer>("publisher_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.users_id_seq</code>
     */
    public static final Sequence<Integer> USERS_ID_SEQ = new SequenceImpl<Integer>("users_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
