/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model;


import ru.sidnystorm.books.model.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.book_academ</code>.
     */
    public static final BookAcadem BOOK_ACADEM = BookAcadem.BOOK_ACADEM;

    /**
     * The table <code>public.book_binom</code>.
     */
    public static final BookBinom BOOK_BINOM = BookBinom.BOOK_BINOM;

    /**
     * The table <code>public.book_drofa</code>.
     */
    public static final BookDrofa BOOK_DROFA = BookDrofa.BOOK_DROFA;

    /**
     * The table <code>public.book_prosvet_bl</code>.
     */
    public static final BookProsvetBl BOOK_PROSVET_BL = BookProsvetBl.BOOK_PROSVET_BL;

    /**
     * The table <code>public.book_prosvet_fp</code>.
     */
    public static final BookProsvetFp BOOK_PROSVET_FP = BookProsvetFp.BOOK_PROSVET_FP;

    /**
     * The table <code>public.book_prosvet_me</code>.
     */
    public static final BookProsvetMe BOOK_PROSVET_ME = BookProsvetMe.BOOK_PROSVET_ME;

    /**
     * The table <code>public.book_prosvet_sh</code>.
     */
    public static final BookProsvetSh BOOK_PROSVET_SH = BookProsvetSh.BOOK_PROSVET_SH;

    /**
     * The table <code>public.book_prosvet_vu</code>.
     */
    public static final BookProsvetVu BOOK_PROSVET_VU = BookProsvetVu.BOOK_PROSVET_VU;

    /**
     * The table <code>public.book_ruword</code>.
     */
    public static final BookRuword BOOK_RUWORD = BookRuword.BOOK_RUWORD;

    /**
     * The table <code>public.book_ventana</code>.
     */
    public static final BookVentana BOOK_VENTANA = BookVentana.BOOK_VENTANA;

    /**
     * The table <code>public.book_xxi</code>.
     */
    public static final BookXxi BOOK_XXI = BookXxi.BOOK_XXI;

    /**
     * The table <code>public.manager</code>.
     */
    public static final Manager MANAGER = Manager.MANAGER;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_book</code>.
     */
    public static final OrderBook ORDER_BOOK = OrderBook.ORDER_BOOK;

    /**
     * The table <code>public.publisher</code>.
     */
    public static final Publisher PUBLISHER = Publisher.PUBLISHER;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
