/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;
import ru.sidnystorm.books.model.Public;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AddressType implements EnumType {

    JURIDICAL("JURIDICAL"),

    MAILING("MAILING"),

    SHIPPING("SHIPPING");

    private final String literal;

    private AddressType(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "address_type";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
