/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookRuwordRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRuword extends TableImpl<BookRuwordRecord> {

    private static final long serialVersionUID = 1655561816;

    /**
     * The reference instance of <code>public.book_ruword</code>
     */
    public static final BookRuword BOOK_RUWORD = new BookRuword();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookRuwordRecord> getRecordType() {
        return BookRuwordRecord.class;
    }

    /**
     * The column <code>public.book_ruword.id</code>.
     */
    public final TableField<BookRuwordRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_ruword_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_ruword.author</code>.
     */
    public final TableField<BookRuwordRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ruword.grade</code>.
     */
    public final TableField<BookRuwordRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ruword.name</code>.
     */
    public final TableField<BookRuwordRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ruword.price</code>.
     */
    public final TableField<BookRuwordRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_ruword</code> table reference
     */
    public BookRuword() {
        this(DSL.name("book_ruword"), null);
    }

    /**
     * Create an aliased <code>public.book_ruword</code> table reference
     */
    public BookRuword(String alias) {
        this(DSL.name(alias), BOOK_RUWORD);
    }

    /**
     * Create an aliased <code>public.book_ruword</code> table reference
     */
    public BookRuword(Name alias) {
        this(alias, BOOK_RUWORD);
    }

    private BookRuword(Name alias, Table<BookRuwordRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookRuword(Name alias, Table<BookRuwordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookRuword(Table<O> child, ForeignKey<O, BookRuwordRecord> key) {
        super(child, key, BOOK_RUWORD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_RUWORD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookRuwordRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_RUWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookRuwordRecord> getPrimaryKey() {
        return Keys.BOOK_RUWORD_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookRuwordRecord>> getKeys() {
        return Arrays.<UniqueKey<BookRuwordRecord>>asList(Keys.BOOK_RUWORD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRuword as(String alias) {
        return new BookRuword(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRuword as(Name alias) {
        return new BookRuword(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookRuword rename(String name) {
        return new BookRuword(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookRuword rename(Name name) {
        return new BookRuword(name, null);
    }
}
