/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookProsvetFpRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookProsvetFp extends TableImpl<BookProsvetFpRecord> {

    private static final long serialVersionUID = -83267537;

    /**
     * The reference instance of <code>public.book_prosvet_fp</code>
     */
    public static final BookProsvetFp BOOK_PROSVET_FP = new BookProsvetFp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookProsvetFpRecord> getRecordType() {
        return BookProsvetFpRecord.class;
    }

    /**
     * The column <code>public.book_prosvet_fp.id</code>.
     */
    public final TableField<BookProsvetFpRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_prosvet_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_prosvet_fp.author</code>.
     */
    public final TableField<BookProsvetFpRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_fp.name</code>.
     */
    public final TableField<BookProsvetFpRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_fp.grade</code>.
     */
    public final TableField<BookProsvetFpRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_fp.price</code>.
     */
    public final TableField<BookProsvetFpRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_prosvet_fp</code> table reference
     */
    public BookProsvetFp() {
        this(DSL.name("book_prosvet_fp"), null);
    }

    /**
     * Create an aliased <code>public.book_prosvet_fp</code> table reference
     */
    public BookProsvetFp(String alias) {
        this(DSL.name(alias), BOOK_PROSVET_FP);
    }

    /**
     * Create an aliased <code>public.book_prosvet_fp</code> table reference
     */
    public BookProsvetFp(Name alias) {
        this(alias, BOOK_PROSVET_FP);
    }

    private BookProsvetFp(Name alias, Table<BookProsvetFpRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookProsvetFp(Name alias, Table<BookProsvetFpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookProsvetFp(Table<O> child, ForeignKey<O, BookProsvetFpRecord> key) {
        super(child, key, BOOK_PROSVET_FP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_PROSVET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookProsvetFpRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_PROSVET_FP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookProsvetFpRecord> getPrimaryKey() {
        return Keys.BOOK_PROSVET_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookProsvetFpRecord>> getKeys() {
        return Arrays.<UniqueKey<BookProsvetFpRecord>>asList(Keys.BOOK_PROSVET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetFp as(String alias) {
        return new BookProsvetFp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetFp as(Name alias) {
        return new BookProsvetFp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetFp rename(String name) {
        return new BookProsvetFp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetFp rename(Name name) {
        return new BookProsvetFp(name, null);
    }
}
