/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookProsvetShRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookProsvetSh extends TableImpl<BookProsvetShRecord> {

    private static final long serialVersionUID = -2127990723;

    /**
     * The reference instance of <code>public.book_prosvet_sh</code>
     */
    public static final BookProsvetSh BOOK_PROSVET_SH = new BookProsvetSh();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookProsvetShRecord> getRecordType() {
        return BookProsvetShRecord.class;
    }

    /**
     * The column <code>public.book_prosvet_sh.id</code>.
     */
    public final TableField<BookProsvetShRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_prosvet_sh_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_prosvet_sh.author</code>.
     */
    public final TableField<BookProsvetShRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_sh.name</code>.
     */
    public final TableField<BookProsvetShRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_sh.grade</code>.
     */
    public final TableField<BookProsvetShRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_sh.price</code>.
     */
    public final TableField<BookProsvetShRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_prosvet_sh</code> table reference
     */
    public BookProsvetSh() {
        this(DSL.name("book_prosvet_sh"), null);
    }

    /**
     * Create an aliased <code>public.book_prosvet_sh</code> table reference
     */
    public BookProsvetSh(String alias) {
        this(DSL.name(alias), BOOK_PROSVET_SH);
    }

    /**
     * Create an aliased <code>public.book_prosvet_sh</code> table reference
     */
    public BookProsvetSh(Name alias) {
        this(alias, BOOK_PROSVET_SH);
    }

    private BookProsvetSh(Name alias, Table<BookProsvetShRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookProsvetSh(Name alias, Table<BookProsvetShRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookProsvetSh(Table<O> child, ForeignKey<O, BookProsvetShRecord> key) {
        super(child, key, BOOK_PROSVET_SH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_PROSVET_SH_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookProsvetShRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_PROSVET_SH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookProsvetShRecord> getPrimaryKey() {
        return Keys.BOOK_PROSVET_SH_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookProsvetShRecord>> getKeys() {
        return Arrays.<UniqueKey<BookProsvetShRecord>>asList(Keys.BOOK_PROSVET_SH_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetSh as(String alias) {
        return new BookProsvetSh(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetSh as(Name alias) {
        return new BookProsvetSh(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetSh rename(String name) {
        return new BookProsvetSh(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetSh rename(Name name) {
        return new BookProsvetSh(name, null);
    }
}
