/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookXxiRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookXxi extends TableImpl<BookXxiRecord> {

    private static final long serialVersionUID = 1120955268;

    /**
     * The reference instance of <code>public.book_xxi</code>
     */
    public static final BookXxi BOOK_XXI = new BookXxi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookXxiRecord> getRecordType() {
        return BookXxiRecord.class;
    }

    /**
     * The column <code>public.book_xxi.id</code>.
     */
    public final TableField<BookXxiRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_xxi_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_xxi.author</code>.
     */
    public final TableField<BookXxiRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_xxi.name</code>.
     */
    public final TableField<BookXxiRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_xxi.grade</code>.
     */
    public final TableField<BookXxiRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_xxi.price</code>.
     */
    public final TableField<BookXxiRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_xxi</code> table reference
     */
    public BookXxi() {
        this(DSL.name("book_xxi"), null);
    }

    /**
     * Create an aliased <code>public.book_xxi</code> table reference
     */
    public BookXxi(String alias) {
        this(DSL.name(alias), BOOK_XXI);
    }

    /**
     * Create an aliased <code>public.book_xxi</code> table reference
     */
    public BookXxi(Name alias) {
        this(alias, BOOK_XXI);
    }

    private BookXxi(Name alias, Table<BookXxiRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookXxi(Name alias, Table<BookXxiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookXxi(Table<O> child, ForeignKey<O, BookXxiRecord> key) {
        super(child, key, BOOK_XXI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_XXI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookXxiRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_XXI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookXxiRecord> getPrimaryKey() {
        return Keys.BOOK_XXI_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookXxiRecord>> getKeys() {
        return Arrays.<UniqueKey<BookXxiRecord>>asList(Keys.BOOK_XXI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookXxi as(String alias) {
        return new BookXxi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookXxi as(Name alias) {
        return new BookXxi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookXxi rename(String name) {
        return new BookXxi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookXxi rename(Name name) {
        return new BookXxi(name, null);
    }
}
