/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookVentanaRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookVentana extends TableImpl<BookVentanaRecord> {

    private static final long serialVersionUID = -1520501088;

    /**
     * The reference instance of <code>public.book_ventana</code>
     */
    public static final BookVentana BOOK_VENTANA = new BookVentana();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookVentanaRecord> getRecordType() {
        return BookVentanaRecord.class;
    }

    /**
     * The column <code>public.book_ventana.id</code>.
     */
    public final TableField<BookVentanaRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_ventana_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_ventana.author</code>.
     */
    public final TableField<BookVentanaRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ventana.name</code>.
     */
    public final TableField<BookVentanaRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ventana.grade</code>.
     */
    public final TableField<BookVentanaRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_ventana.price</code>.
     */
    public final TableField<BookVentanaRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_ventana</code> table reference
     */
    public BookVentana() {
        this(DSL.name("book_ventana"), null);
    }

    /**
     * Create an aliased <code>public.book_ventana</code> table reference
     */
    public BookVentana(String alias) {
        this(DSL.name(alias), BOOK_VENTANA);
    }

    /**
     * Create an aliased <code>public.book_ventana</code> table reference
     */
    public BookVentana(Name alias) {
        this(alias, BOOK_VENTANA);
    }

    private BookVentana(Name alias, Table<BookVentanaRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookVentana(Name alias, Table<BookVentanaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookVentana(Table<O> child, ForeignKey<O, BookVentanaRecord> key) {
        super(child, key, BOOK_VENTANA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_VENTANA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookVentanaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_VENTANA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookVentanaRecord> getPrimaryKey() {
        return Keys.BOOK_VENTANA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookVentanaRecord>> getKeys() {
        return Arrays.<UniqueKey<BookVentanaRecord>>asList(Keys.BOOK_VENTANA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookVentana as(String alias) {
        return new BookVentana(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookVentana as(Name alias) {
        return new BookVentana(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookVentana rename(String name) {
        return new BookVentana(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookVentana rename(Name name) {
        return new BookVentana(name, null);
    }
}
