/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookDrofaRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookDrofa extends TableImpl<BookDrofaRecord> {

    private static final long serialVersionUID = 93112738;

    /**
     * The reference instance of <code>public.book_drofa</code>
     */
    public static final BookDrofa BOOK_DROFA = new BookDrofa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookDrofaRecord> getRecordType() {
        return BookDrofaRecord.class;
    }

    /**
     * The column <code>public.book_drofa.id</code>.
     */
    public final TableField<BookDrofaRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_drofa_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_drofa.author</code>.
     */
    public final TableField<BookDrofaRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_drofa.name</code>.
     */
    public final TableField<BookDrofaRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_drofa.grade</code>.
     */
    public final TableField<BookDrofaRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_drofa.price</code>.
     */
    public final TableField<BookDrofaRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_drofa</code> table reference
     */
    public BookDrofa() {
        this(DSL.name("book_drofa"), null);
    }

    /**
     * Create an aliased <code>public.book_drofa</code> table reference
     */
    public BookDrofa(String alias) {
        this(DSL.name(alias), BOOK_DROFA);
    }

    /**
     * Create an aliased <code>public.book_drofa</code> table reference
     */
    public BookDrofa(Name alias) {
        this(alias, BOOK_DROFA);
    }

    private BookDrofa(Name alias, Table<BookDrofaRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookDrofa(Name alias, Table<BookDrofaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookDrofa(Table<O> child, ForeignKey<O, BookDrofaRecord> key) {
        super(child, key, BOOK_DROFA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_DROFA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookDrofaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_DROFA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookDrofaRecord> getPrimaryKey() {
        return Keys.BOOK_DROFA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookDrofaRecord>> getKeys() {
        return Arrays.<UniqueKey<BookDrofaRecord>>asList(Keys.BOOK_DROFA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookDrofa as(String alias) {
        return new BookDrofa(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookDrofa as(Name alias) {
        return new BookDrofa(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookDrofa rename(String name) {
        return new BookDrofa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookDrofa rename(Name name) {
        return new BookDrofa(name, null);
    }
}
