/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookProsvetMeRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookProsvetMe extends TableImpl<BookProsvetMeRecord> {

    private static final long serialVersionUID = -612843061;

    /**
     * The reference instance of <code>public.book_prosvet_me</code>
     */
    public static final BookProsvetMe BOOK_PROSVET_ME = new BookProsvetMe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookProsvetMeRecord> getRecordType() {
        return BookProsvetMeRecord.class;
    }

    /**
     * The column <code>public.book_prosvet_me.id</code>.
     */
    public final TableField<BookProsvetMeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_prosvet_me_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_prosvet_me.author</code>.
     */
    public final TableField<BookProsvetMeRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_me.name</code>.
     */
    public final TableField<BookProsvetMeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_me.grade</code>.
     */
    public final TableField<BookProsvetMeRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_me.price</code>.
     */
    public final TableField<BookProsvetMeRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_prosvet_me</code> table reference
     */
    public BookProsvetMe() {
        this(DSL.name("book_prosvet_me"), null);
    }

    /**
     * Create an aliased <code>public.book_prosvet_me</code> table reference
     */
    public BookProsvetMe(String alias) {
        this(DSL.name(alias), BOOK_PROSVET_ME);
    }

    /**
     * Create an aliased <code>public.book_prosvet_me</code> table reference
     */
    public BookProsvetMe(Name alias) {
        this(alias, BOOK_PROSVET_ME);
    }

    private BookProsvetMe(Name alias, Table<BookProsvetMeRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookProsvetMe(Name alias, Table<BookProsvetMeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookProsvetMe(Table<O> child, ForeignKey<O, BookProsvetMeRecord> key) {
        super(child, key, BOOK_PROSVET_ME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_PROSVET_ME_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookProsvetMeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_PROSVET_ME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookProsvetMeRecord> getPrimaryKey() {
        return Keys.BOOK_PROSVET_ME_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookProsvetMeRecord>> getKeys() {
        return Arrays.<UniqueKey<BookProsvetMeRecord>>asList(Keys.BOOK_PROSVET_ME_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetMe as(String alias) {
        return new BookProsvetMe(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetMe as(Name alias) {
        return new BookProsvetMe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetMe rename(String name) {
        return new BookProsvetMe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetMe rename(Name name) {
        return new BookProsvetMe(name, null);
    }
}
