/*
 * This file is generated by jOOQ.
 */
package ru.sidnystorm.books.model.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import ru.sidnystorm.books.model.Indexes;
import ru.sidnystorm.books.model.Keys;
import ru.sidnystorm.books.model.Public;
import ru.sidnystorm.books.model.tables.records.BookProsvetVuRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookProsvetVu extends TableImpl<BookProsvetVuRecord> {

    private static final long serialVersionUID = -750735999;

    /**
     * The reference instance of <code>public.book_prosvet_vu</code>
     */
    public static final BookProsvetVu BOOK_PROSVET_VU = new BookProsvetVu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookProsvetVuRecord> getRecordType() {
        return BookProsvetVuRecord.class;
    }

    /**
     * The column <code>public.book_prosvet_vu.id</code>.
     */
    public final TableField<BookProsvetVuRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('book_prosvet_vu_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.book_prosvet_vu.author</code>.
     */
    public final TableField<BookProsvetVuRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_vu.name</code>.
     */
    public final TableField<BookProsvetVuRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_vu.grade</code>.
     */
    public final TableField<BookProsvetVuRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.book_prosvet_vu.price</code>.
     */
    public final TableField<BookProsvetVuRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>public.book_prosvet_vu</code> table reference
     */
    public BookProsvetVu() {
        this(DSL.name("book_prosvet_vu"), null);
    }

    /**
     * Create an aliased <code>public.book_prosvet_vu</code> table reference
     */
    public BookProsvetVu(String alias) {
        this(DSL.name(alias), BOOK_PROSVET_VU);
    }

    /**
     * Create an aliased <code>public.book_prosvet_vu</code> table reference
     */
    public BookProsvetVu(Name alias) {
        this(alias, BOOK_PROSVET_VU);
    }

    private BookProsvetVu(Name alias, Table<BookProsvetVuRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookProsvetVu(Name alias, Table<BookProsvetVuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BookProsvetVu(Table<O> child, ForeignKey<O, BookProsvetVuRecord> key) {
        super(child, key, BOOK_PROSVET_VU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_PROSVET_VU_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookProsvetVuRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_PROSVET_VU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookProsvetVuRecord> getPrimaryKey() {
        return Keys.BOOK_PROSVET_VU_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookProsvetVuRecord>> getKeys() {
        return Arrays.<UniqueKey<BookProsvetVuRecord>>asList(Keys.BOOK_PROSVET_VU_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetVu as(String alias) {
        return new BookProsvetVu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookProsvetVu as(Name alias) {
        return new BookProsvetVu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetVu rename(String name) {
        return new BookProsvetVu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookProsvetVu rename(Name name) {
        return new BookProsvetVu(name, null);
    }
}
